### ISSUE TITLE
but why

### ISSUE THREAD

**Issue by mavdotj** [katlyn/fops#2]
# why? 😭

**Comment by katlyn** [comment]
Because fops good. Additionally:

https://github.com/katlyn/fops/assets/17418611/d6586f26-6017-41a9-9bb9-309d82cbd841


(via [@volpeon@is-a.wyvern.rip](https://is-a.wyvern.rip/notes/9tmkbazakzlk08vq))

**Comment by mavdotj** [comment]
valid reason
